#pragma kernel GenerateIBLLut

#include "../shaders/IBL.hlsl"

float _Width;
float _Height;
RWTexture2D<float4> _ResultLut;

[numthreads(8, 8, 1)]
void GenerateIBLLut(uint3 id : SV_DispatchThreadID) {
    float NdotV = ((float) id.x) / _Width;
    float roughness = ((float) id.y) / _Height;
    float linearRoughness = sqrt(roughness);
    
    _ResultLut[id.xy] = PrecomputeL_DFG(NdotV, linearRoughness);
} 
